### ISSUE TITLE
"Not authorized to send Apple events to System Events"

### ISSUE THREAD

**Issue by damacguy** [jamf/Jamf-Pro-Object-LookUp#5]
I can't add Terminal to Automation in Security, and I've tried a PPPC. Maybe have an option to use the terminal to prompt for options instead of using AppleScript (love AS, but...).
Something like this...

> Please make your selection:
> [1] Packages
> [2] Scripts
> [3] Printers
> [4] Computer Groups
> [5] Mobile Device Groups

**Comment by daniel-maclaughlin** [comment]
Hi @damacguy,
It is something I can look into, I opted for AppleScript dialog first since it handled large lists better, you can imagine after selections say packages, and you have 50+ packages scrolling through in terminal to find them can be challenging. I'll look into it as a feature request.
will close this for now
Thanks for trying it out though

**Comment by daniel-maclaughlin** [comment]
@damacguy 
latest version of this script I removed the System events from the apple script prompts so that it won't require approval.
will look into a terminal prompt too but hope that helps in the interim.

Regards,

Daniel MacLaughlin
